-- Limpeza das tabelas Neuron (ordem compatível com as FKs).

DROP TABLE T_NRON_RESP_FORMULARIO CASCADE CONSTRAINTS;
DROP TABLE T_NRON_REGIST_EMOCAO CASCADE CONSTRAINTS;
DROP TABLE T_NRON_EMOCAO CASCADE CONSTRAINTS;
DROP TABLE T_NRON_USUARIO CASCADE CONSTRAINTS;
DROP TABLE T_NRON_DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE T_NRON_CATG_EMOCAO CASCADE CONSTRAINTS;
DROP TABLE T_NRON_ACESSO CASCADE CONSTRAINTS;
