-- Gerado originalmente no Oracle SQL Developer Data Modeler 24.3.1.351.0831
-- Adaptado para o repositório Neuron.

CREATE TABLE T_NRON_ACESSO 
(
  ID_ACESSO NUMBER(5) NOT NULL,
  TP_ACESSO VARCHAR2(50 CHAR) NOT NULL,
  DS_ACESSO VARCHAR2(255 CHAR) NOT NULL
);

ALTER TABLE T_NRON_ACESSO 
  ADD CONSTRAINT T_NRON_ACESSO_PK PRIMARY KEY (ID_ACESSO);

COMMENT ON COLUMN T_NRON_ACESSO.ID_ACESSO IS 'ID DO TIPO DE ACESSO';
COMMENT ON COLUMN T_NRON_ACESSO.TP_ACESSO IS 'TIPO DE ACESSO (CHECK) -> FUNCIONARIO, GESTOR, RH_CLEVEL';
COMMENT ON COLUMN T_NRON_ACESSO.DS_ACESSO IS 'DESCRICAO DO TIPO DE ACESSO';


CREATE TABLE T_NRON_CATG_EMOCAO 
(
  ID_CATG_EMOCAO NUMBER(5) NOT NULL,
  NOME_CATG_EMOCAO VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE T_NRON_CATG_EMOCAO
  ADD CONSTRAINT CK_NOME_CATG_EMOCAO CHECK 
  (NOME_CATG_EMOCAO IN ('NEGATIVA', 'NEUTRA', 'POSITIVA'));

ALTER TABLE T_NRON_CATG_EMOCAO
  ADD CONSTRAINT T_NRON_CATG_EMOCAO_PK PRIMARY KEY (ID_CATG_EMOCAO);


CREATE TABLE T_NRON_DEPARTAMENTO 
(
  ID_DEPARTAMENTO NUMBER(5) NOT NULL,
  NOME_DEPARTAMENTO VARCHAR2(100 CHAR) NOT NULL,
  DS_DEPARTAMENTO VARCHAR2(150 CHAR) NOT NULL
);

ALTER TABLE T_NRON_DEPARTAMENTO 
  ADD CONSTRAINT T_NRON_DEPARTAMENTO_PK PRIMARY KEY (ID_DEPARTAMENTO);


CREATE TABLE T_NRON_EMOCAO 
(
  ID_EMOCAO NUMBER(5) NOT NULL,
  NM_EMOCAO VARCHAR2(30 CHAR) NOT NULL,
  COR_EMOCAO VARCHAR2(10 BYTE) NOT NULL,
  ID_CATG_EMOCAO NUMBER(5) NOT NULL
);

ALTER TABLE T_NRON_EMOCAO
  ADD CONSTRAINT T_NRON_EMOCAO_PK PRIMARY KEY (ID_EMOCAO);


CREATE TABLE T_NRON_REGIST_EMOCAO 
(
  ID_REGIST_EMOCAO NUMBER(5) NOT NULL,
  INT_REGIST_EMOCAO NUMBER(3,1) NOT NULL,
  DS_REGIST_EMOCAO VARCHAR2(255 CHAR) NOT NULL,
  DT_REGIST_EMOCAO DATE NOT NULL,
  ID_EMOCAO NUMBER(5) NOT NULL
);

ALTER TABLE T_NRON_REGIST_EMOCAO
  ADD CONSTRAINT INT_REGIST_EMOCAO CHECK (INT_REGIST_EMOCAO BETWEEN 0.0 AND 10.0);

ALTER TABLE T_NRON_REGIST_EMOCAO
  ADD CONSTRAINT T_NRON_REGIST_EMOCAO_PK PRIMARY KEY (ID_REGIST_EMOCAO);


CREATE TABLE T_NRON_RESP_FORMULARIO 
(
  ID_RESPOSTA NUMBER(5) NOT NULL,
  DT_RESPOSTA DATE NOT NULL,
  MOT_RESPOSTA NUMBER(3,1) NOT NULL,
  FEL_RESPOSTA NUMBER(3,1) NOT NULL,
  EST_RESPOSTA NUMBER(3,1) NOT NULL,
  OBS_RESPOSTA VARCHAR2(250 CHAR) NOT NULL,
  SAU_MEN_RESPOSTA NUMBER(4,1) NOT NULL,
  PROB_RESPOSTA NUMBER(6,3) NOT NULL,
  MOD_VER_RESPOSTA VARCHAR2(20 CHAR) NOT NULL,
  DT_ANL_RESPOSTA DATE NOT NULL,
  ID_USUARIO NUMBER(5) NOT NULL,
  ID_REGIST_EMOCAO NUMBER(5) NOT NULL
);

ALTER TABLE T_NRON_RESP_FORMULARIO
  ADD CONSTRAINT CK_MOT_RESPOSTA CHECK (MOT_RESPOSTA BETWEEN 0.0 AND 10.0);

ALTER TABLE T_NRON_RESP_FORMULARIO
  ADD CONSTRAINT CK_FEL_RESPOSTA CHECK (FEL_RESPOSTA BETWEEN 0.0 AND 10.0);

ALTER TABLE T_NRON_RESP_FORMULARIO
  ADD CONSTRAINT T_NRON_RESP_FORMULARIO_PK PRIMARY KEY (ID_RESPOSTA);


CREATE TABLE T_NRON_USUARIO 
(
  ID_USUARIO NUMBER(5) NOT NULL,
  NOME VARCHAR2(150 CHAR) NOT NULL,
  EM_USUARIO VARCHAR2(150 CHAR) NOT NULL,
  SEN_HASH_USUARIO VARCHAR2(255 CHAR) NOT NULL,
  STT_USUARIO CHAR(1) NOT NULL,
  DT_CADASTRO DATE NOT NULL,
  ID_ACESSO NUMBER(5) NOT NULL,
  ID_DEPARTAMENTO NUMBER(5) NOT NULL
);

ALTER TABLE T_NRON_USUARIO
  ADD CONSTRAINT T_NRON_USUARIO_PK PRIMARY KEY (ID_USUARIO);

ALTER TABLE T_NRON_USUARIO
  ADD CONSTRAINT UK_NRON_EM_USUARIO UNIQUE (EM_USUARIO);

ALTER TABLE T_NRON_EMOCAO
  ADD CONSTRAINT FK_CATG_EMOCAO_EMOCAO FOREIGN KEY (ID_CATG_EMOCAO)
  REFERENCES T_NRON_CATG_EMOCAO (ID_CATG_EMOCAO);

ALTER TABLE T_NRON_USUARIO
  ADD CONSTRAINT FK_ACESSO_USUARIO FOREIGN KEY (ID_ACESSO)
  REFERENCES T_NRON_ACESSO (ID_ACESSO);

ALTER TABLE T_NRON_USUARIO
  ADD CONSTRAINT FK_DEPARTAMENTO_USUARIO FOREIGN KEY (ID_DEPARTAMENTO)
  REFERENCES T_NRON_DEPARTAMENTO (ID_DEPARTAMENTO);

ALTER TABLE T_NRON_REGIST_EMOCAO
  ADD CONSTRAINT FK_EMOCAO_REGIST_EMOCAO FOREIGN KEY (ID_EMOCAO)
  REFERENCES T_NRON_EMOCAO (ID_EMOCAO);

ALTER TABLE T_NRON_RESP_FORMULARIO
  ADD CONSTRAINT FK_REGIST_EMOCAO_RESP_FORM FOREIGN KEY (ID_REGIST_EMOCAO)
  REFERENCES T_NRON_REGIST_EMOCAO (ID_REGIST_EMOCAO);

ALTER TABLE T_NRON_RESP_FORMULARIO
  ADD CONSTRAINT FK_USUARIO_RESP_FORM FOREIGN KEY (ID_USUARIO)
  REFERENCES T_NRON_USUARIO (ID_USUARIO);

ALTER TABLE T_NRON_RESP_FORMULARIO
  ADD CONSTRAINT UNQ_RESP_REGIST UNIQUE (ID_REGIST_EMOCAO);
